In [1]:
import tensorflow as tf

In [2]:
tf

<module 'tensorflow' from 'C:\\Users\\rajesh\\AppData\\Roaming\\Python\\Python311\\site-packages\\tensorflow\\__init__.py'>

In [5]:
help(tf.__init__)

Help on method-wrapper:

__init__(*args, **kwargs)
    Initialize self.  See help(type(self)) for accurate signature.



In [6]:
import numpy as np

In [7]:
np


<module 'numpy' from 'C:\\ProgramData\\anaconda3\\Lib\\site-packages\\numpy\\__init__.py'>

##### Create Tensor

In [42]:
a = tf.constant([1,2,3,4])
b = tf.constant([5,6,7,8])

In [43]:
print("Tesnor a:", a)
print("Tesnor b:", b)

Tesnor a: tf.Tensor([1 2 3 4], shape=(4,), dtype=int32)
Tesnor b: tf.Tensor([5 6 7 8], shape=(4,), dtype=int32)


In [44]:
a2 = tf.constant([[[[1,2,5],[3,4,5]],[[1,2,5],[3,4,5]]],[[[1,2,5],[3,4,5]],[[1,2,5],[3,4,5]]]])
a2

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[1, 2, 5],
         [3, 4, 5]],

        [[1, 2, 5],
         [3, 4, 5]]],


       [[[1, 2, 5],
         [3, 4, 5]],

        [[1, 2, 5],
         [3, 4, 5]]]])>

In [45]:
2*a2

<tf.Tensor: shape=(2, 2, 2, 3), dtype=int32, numpy=
array([[[[ 2,  4, 10],
         [ 6,  8, 10]],

        [[ 2,  4, 10],
         [ 6,  8, 10]]],


       [[[ 2,  4, 10],
         [ 6,  8, 10]],

        [[ 2,  4, 10],
         [ 6,  8, 10]]]])>

In [46]:
a2.numpy()

array([[[[1, 2, 5],
         [3, 4, 5]],

        [[1, 2, 5],
         [3, 4, 5]]],


       [[[1, 2, 5],
         [3, 4, 5]],

        [[1, 2, 5],
         [3, 4, 5]]]])

In [50]:
a = tf.constant([1,2,3,16])
b = tf.constant([5,6,7,8])

In [51]:
d = tf.subtract(a,b)
print(d)

tf.Tensor([-4 -4 -4  8], shape=(4,), dtype=int32)


In [58]:
a/b

<tf.Tensor: shape=(4,), dtype=float64, numpy=array([0.2       , 0.33333333, 0.42857143, 2.        ])>

In [59]:
a//b

<tf.Tensor: shape=(4,), dtype=int32, numpy=array([0, 0, 0, 2])>

In [57]:
type(8//2)

int

In [65]:
c = tf.constant([[1,2],[3,16]])
d = tf.constant([[5,6],[7,8]])
(tf.matmul(c,d)).numpy()

array([[ 19,  22],
       [127, 146]])

In [67]:
print(c.dtype)

<dtype: 'int32'>
